export const CISA_SECTORS = [
  'Chemical',
  'Commercial Facilities',
  'Communications',
  'Critical Manufacturing',
  'Dams',
  'Defense Industrial Base',
  'Emergency Services',
  'Energy',
  'Financial Services',
  'Food and Agriculture',
  'Government Facilities',
  'Healthcare and Public Health',
  'Information Technology',
  'Nuclear Reactors, Materials, and Waste',
  'Transportation Systems',
  'Water and Wastewater Systems',
  'Cross-Sector'
] as const

export type CISASector = (typeof CISA_SECTORS)[number]

export interface ComplianceFramework {
  id: string
  name: string
}

export const COMPLIANCE_FRAMEWORKS: ComplianceFramework[] = [
  { id: 'IEC_62443_3_3', name: 'IEC 62443-3-3' },
  { id: 'IEC_62443_4_2', name: 'IEC 62443-4-2' },
  { id: 'NIST_800_82', name: 'NIST SP 800-82 r3' },
  { id: 'NIST_800_53', name: 'NIST SP 800-53 r5' },
  { id: 'NIST_CSF', name: 'NIST CSF v2.0' },
  { id: 'CISA_CPG', name: 'CISA Cross-Sector CPGs' },
  { id: 'CIS_CONTROLS', name: 'CIS Controls v8' },
  { id: 'NERC_CIP_002', name: 'NERC CIP-002' },
  { id: 'NERC_CIP_003', name: 'NERC CIP-003' },
  { id: 'NERC_CIP_004', name: 'NERC CIP-004' },
  { id: 'NERC_CIP_005', name: 'NERC CIP-005' },
  { id: 'NERC_CIP_006', name: 'NERC CIP-006' },
  { id: 'NERC_CIP_007', name: 'NERC CIP-007' },
  { id: 'NERC_CIP_008', name: 'NERC CIP-008' },
  { id: 'NERC_CIP_009', name: 'NERC CIP-009' },
  { id: 'NERC_CIP_010', name: 'NERC CIP-010' },
  { id: 'NERC_CIP_011', name: 'NERC CIP-011' },
  { id: 'NERC_CIP_013', name: 'NERC CIP-013' },
  { id: 'NERC_CIP_014', name: 'NERC CIP-014' },
  { id: 'ISO_27019', name: 'ISO 27019' },
  { id: 'NISTIR_7628', name: 'NISTIR 7628' },
  { id: 'INGAA_GUIDE', name: 'INGAA Guidelines' },
  { id: 'API_1164', name: 'API Standard 1164' },
  { id: 'IEEE_1686', name: 'IEEE 1686' },
  { id: 'NRC_RG_5_71', name: 'NRC Reg Guide 5.71' },
  { id: 'IAEA_NSS_17', name: 'IAEA NSS-17' },
  { id: 'AWWA_G430', name: 'AWWA G430' },
  { id: 'EPA_WATER', name: 'EPA Baseline' },
  { id: 'AWWA_M19', name: 'AWWA M19' },
  { id: 'NIST_800_171', name: 'NIST SP 800-171' },
  { id: 'NIST_800_172', name: 'NIST SP 800-172' },
  { id: 'CMMC_L1', name: 'CMMC Level 1' },
  { id: 'CMMC_L2', name: 'CMMC Level 2' },
  { id: 'CMMC_L3', name: 'CMMC Level 3' },
  { id: 'CNSSI_1253', name: 'CNSSI 1253' },
  { id: 'NNSA_NAP_24', name: 'NNSA NAP-24A' },
  { id: 'TSA_PIPELINE', name: 'TSA Pipeline' },
  { id: 'TSA_RAIL', name: 'TSA Rail' },
  { id: 'FAA_AIRPORT', name: 'FAA Airport' },
  { id: 'USCG_MARITIME', name: 'USCG Maritime' },
  { id: 'DO_326A', name: 'DO-326A' },
  { id: 'CFATS_RBPS', name: 'CFATS RBPS' },
  { id: 'ANSSI_BP_006', name: 'ANSSI BP-006' },
  { id: 'BSI_IT_GRUNDSCHUTZ', name: 'BSI IT-Grundschutz' },
  { id: 'DHS_CATALOG', name: 'DHS Catalog' },
  { id: 'ISA_99_LEGACY', name: 'ISA-99' },
  { id: 'ISO_27001', name: 'ISO 27001' },
  { id: 'COBIT_2019', name: 'COBIT 2019' },
  { id: 'HIPAA_SECURITY', name: 'HIPAA Security' },
  { id: 'SOC_2', name: 'SOC 2 Type II' },
  { id: 'PCI_DSS', name: 'PCI-DSS' },
  { id: 'CSA_CCM', name: 'CSA CCM' },
  { id: 'ACSC_ESSENTIAL_8', name: 'ACSC Essential 8' },
  { id: 'SWIFT_CSCF', name: 'SWIFT CSCF' },
  { id: 'CRI_PROFILE', name: 'CRI Profile' },
  { id: 'KATRI_SCADA', name: 'KATRI SCADA' },
  { id: 'NIST_800_37', name: 'NIST SP 800-37' },
  { id: 'NIST_800_161', name: 'NIST SP 800-161' },
  { id: 'ENISA_IOT', name: 'ENISA IoT Guidelines' },
  { id: 'NIS2', name: 'EU NIS2 Directive' },
  { id: 'CRA', name: 'EU Cyber Resilience Act' },
  { id: 'SOCI_ACT', name: 'Australian SOCI Act' },
]
