import asyncio
import os
import queue
import sys
import threading
import traceback
from datetime import datetime

from loguru import logger
from surrealdb import AsyncSurreal

# Thread-local storage to prevent logging recursion within the same thread.
_local = threading.local()

class SurrealLogSink:
    """
    Loguru sink that queues log messages and writes them to SurrealDB in batches
    using a background thread to prevent blocking main execution paths.
    """
    def __init__(self, component: str):
        self.component = component
        self.queue = queue.Queue(maxsize=10000)
        self.thread = threading.Thread(
            target=self._run_worker, 
            name=f"log_db_worker_{component}", 
            daemon=True
        )
        self.thread.start()

    def _run_worker(self):
        # Permanently set the re-entry guard on the background worker thread.
        # This completely prevents logs generated by the SurrealDB driver or 
        # websockets layer inside this thread from triggering the sink again.
        _local.in_db_sink = True
        
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        loop.run_until_complete(self._process_queue())

    async def _process_queue(self):
        db = None
        
        # 1. Database Connection Helpers
        def get_db_url():
            surreal_url = os.getenv("SURREAL_URL")
            if surreal_url:
                return surreal_url
            address = os.getenv("SURREAL_ADDRESS", "localhost")
            port = os.getenv("SURREAL_PORT", "8000")
            return f"ws://{address}/rpc:{port}"

        def get_db_password():
            return os.getenv("SURREAL_PASSWORD") or os.getenv("SURREAL_PASS")

        async def connect_db():
            nonlocal db
            url = get_db_url()
            password = get_db_password()
            user = os.environ.get("SURREAL_USER")
            ns = os.environ.get("SURREAL_NAMESPACE")
            database = os.environ.get("SURREAL_DATABASE")
            
            db = AsyncSurreal(url)
            await db.signin({"username": user, "password": password})
            await db.use(ns, database)

        # Connect initially
        attempt = 1
        while True:
            try:
                await connect_db()
                sys.stderr.write(f"[SurrealLogSink] Connected to SurrealDB for component: {self.component}\n")
                break
            except Exception as e:
                sys.stderr.write(f"[SurrealLogSink] Initial connection failed (attempt {attempt}): {e}. Retrying in 5s...\n")
                if db:
                    try:
                        await db.close()
                    except:
                        pass
                attempt += 1
                await asyncio.sleep(5)

        # 2. Main Ingestion Loop
        while True:
            try:
                # Wait for at least one log record
                log_records = []
                try:
                    record = self.queue.get(timeout=1.0)
                    log_records.append(record)
                except queue.Empty:
                    continue

                # Batch drain up to 100 pending logs from the queue
                while len(log_records) < 100:
                    try:
                        record = self.queue.get_nowait()
                        log_records.append(record)
                    except queue.Empty:
                        break

                # Write batch to SurrealDB
                if log_records:
                    await db.query("INSERT INTO system_log $data;", {"data": log_records})
                    for _ in range(len(log_records)):
                        self.queue.task_done()
            except Exception as e:
                sys.stderr.write(f"[SurrealLogSink] Error writing logs: {e}\n")
                # Try to clean up connection
                try:
                    await db.close()
                except:
                    pass
                
                # Reconnection loop
                while True:
                    try:
                        await connect_db()
                        sys.stderr.write(f"[SurrealLogSink] Reconnected to SurrealDB for component: {self.component}\n")
                        break
                    except Exception as recon_err:
                        sys.stderr.write(f"[SurrealLogSink] Reconnection failed: {recon_err}. Retrying in 5s...\n")
                        await asyncio.sleep(5)

    def write(self, message):
        """Called by Loguru to process a formatted log record."""
        # 1. Thread-local recursion guard check
        if getattr(_local, "in_db_sink", False):
            return
        
        try:
            _local.in_db_sink = True
            record = message.record
            
            # 2. Namespace / package filtering to avoid recursion loops
            name = record["name"]
            ignored_names = {
                "surrealdb",
                "websockets",
                "asyncio",
                "httpcore",
                "httpx",
                "urllib3",
                "connectionpool",
                "open_notebook.database.repository",
                "open_notebook.database.async_migrate",
                "open_notebook.database",
                "api.routers.system_logs",
            }
            # Also filter out dependencies used by standard libraries/drivers
            for ignored in ignored_names:
                if name == ignored or name.startswith(ignored + "."):
                    return

            # 3. Format exception trace
            exc_str = None
            if record["exception"]:
                exc_str = "".join(traceback.format_exception(*record["exception"]))

            # 4. Construct payload
            payload = {
                "timestamp": record["time"].isoformat(),
                "level": record["level"].name,
                "component": self.component,
                "message": record["message"],
                "module": record["module"],
                "function": record["function"],
                "line": record["line"],
                "exception": exc_str,
                "extra": record.get("extra", {})
            }

            # 5. Queue payload safely
            try:
                self.queue.put_nowait(payload)
            except queue.Full:
                sys.stderr.write(f"[SurrealLogSink] Queue full, dropped log from {self.component}: {payload['message'][:50]}...\n")
        except Exception as err:
            sys.stderr.write(f"[SurrealLogSink] Sink write failure: {err}\n")
        finally:
            _local.in_db_sink = False


def setup_db_logging(component_name: str):
    """
    Set up the SurrealDB logging sink for Loguru.
    Ensures that logs are duplicated to the database while preserving standard console outputs.
    """
    # Read the level from environment, default to INFO to avoid DB bloat with DEBUG noise
    db_log_level = os.environ.get("DB_LOG_LEVEL", "INFO")
    
    sink = SurrealLogSink(component_name)
    logger.add(sink, level=db_log_level, serialize=False)
    logger.info(f"SurrealDB logging sink registered for component: '{component_name}' at level: '{db_log_level}'")
